version: '3'

services:
  ui-consumer-portal:
    image: registry.sekomy.com/lottcp-ui:0.0.0
    container_name: ui-consumer-portal
    environment:
      - BACKEND_PORT=8000
    external_links:
      - consumer-portal:backend
    volumes:
      - /home/lottw/silinecek/static/:/var/lib/nginx/html/static/
      - /home/lottw/silinecek/media/:/var/lib/nginx/html/media/
      - /home/lottw/silinecek/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - 81:80

networks:
  default:
    external:
      name: lott